
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopper_backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - MONGO_URI=mongodb://mongo:27017/shopper-rides
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: shopper_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # seeder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: shopper_seeder
  #   command: "ts-node /app/src/scripts/seedDrivers.ts"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - .:/app

volumes:
  mongo-data: {}

